CREATE TABLE IF NOT EXISTS guests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    rsvp_code VARCHAR(32) NOT NULL,
    rsvp_status VARCHAR(16) NOT NULL,
    rsvp_by TIMESTAMP,
    side VARCHAR(10) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    notes VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_guests_rsvp_code
    ON guests (rsvp_code);

CREATE TABLE IF NOT EXISTS gifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    value NUMERIC(10, 2) NOT NULL,
    total_quotas INTEGER NOT NULL,
    image_url VARCHAR(255),
    purchase_link VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS gift_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gift_id BIGINT NOT NULL,
    guest_name VARCHAR(120) NOT NULL,
    number_quotas INTEGER NOT NULL,
    status VARCHAR(16) NOT NULL,
    reserved_at TIMESTAMP,
    reserved_until TIMESTAMP,
    purchased_at TIMESTAMP,
    CONSTRAINT fk_gift_transactions_gift
        FOREIGN KEY (gift_id) REFERENCES gifts (id)
);

CREATE INDEX IF NOT EXISTS idx_gift_transactions_gift_id
    ON gift_transactions (gift_id);

CREATE INDEX IF NOT EXISTS idx_gift_transactions_expiration
    ON gift_transactions (status, reserved_until);
