CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(64) NOT NULL,
    type VARCHAR(32) NOT NULL,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    event_date_time TIMESTAMP,
    venue_name VARCHAR(120),
    address VARCHAR(255),
    map_url VARCHAR(500),
    dress_code VARCHAR(1000),
    CONSTRAINT uk_events_slug UNIQUE (slug),
    CONSTRAINT uk_events_type UNIQUE (type)
);

INSERT INTO events (slug, type, title)
VALUES
    ('casamento', 'WEDDING', 'Casamento'),
    ('cha-de-panelas', 'BRIDAL_SHOWER', 'Chá de panelas');

CREATE TABLE event_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    guest_id BIGINT NOT NULL,
    rsvp_status VARCHAR(16) NOT NULL,
    responded_at TIMESTAMP,
    notes VARCHAR(255),
    CONSTRAINT fk_event_invitations_event
        FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_invitations_guest
        FOREIGN KEY (guest_id) REFERENCES guests (id) ON DELETE CASCADE,
    CONSTRAINT uk_event_invitations_event_guest UNIQUE (event_id, guest_id)
);

CREATE INDEX idx_event_invitations_event_status
    ON event_invitations (event_id, rsvp_status);

CREATE INDEX idx_event_invitations_guest
    ON event_invitations (guest_id);

INSERT INTO event_invitations (event_id, guest_id, rsvp_status, responded_at, notes)
SELECT event.id, guest.id, guest.rsvp_status, guest.rsvp_by, guest.notes
FROM guests guest
JOIN events event ON event.type = 'WEDDING';

INSERT INTO event_invitations (event_id, guest_id, rsvp_status)
SELECT event.id, guest.id, 'PENDING'
FROM guests guest
JOIN events event ON event.type = 'BRIDAL_SHOWER';

ALTER TABLE guests
    DROP COLUMN rsvp_status,
    DROP COLUMN rsvp_by,
    DROP COLUMN notes;
